import { FontType } from 'src/common/models/base';
import { BackgroundTheme } from 'src/team/enums';

const lightThemeValues = {
  landingPageBackgroundColor: '#131418',
  landingPageBackgroundTopLayerColor: '#14264b',
  landingPageBackgroundBottomLayerColor: '#e41e2e',
  landingPageCardColor: '#14264b',
  landingPageTextColor: '#ffffff',
  authInputBackgroundColor: '#ffffff',
  mainPageBackgroundColor: '#f5f5f5',
  mainPageHeaderColor: '#ffffff',
  mainPageSidebarColor: '#ffffff',
  mainPageCardColor: '#ffffff',
  primaryTextColor: '#2f2f2f',
  secondaryTextColor: '#6b6b6b',
  headingTextColor: '#e41e2e',
  menuTextColor: '#6b6b6b',
  primaryButtonColor: '#e41e2e',
  secondaryButtonColor: '#596169',
  modalBackgroundColor: '#ffffff',
  tabHighlightColor: '#e41e2e',
  buttonTextColor: '#ffffff',
  tokenTextColor: '#e41e2e',
  kudosTextColor: '#feb201',
  kudosIconColor: '#fd5900',
  dateTextColor: '#14264b',
  successColor: '#33be51',
  errorColor: '#ff0000',
  warningColor: '#feb201',
  iconColor: '#e41e2e',
  membershipTierOneColor: '#c6cfd9',
  membershipTierTwoColor: '#9eddff',
  membershipTierThreeColor: '#ee7fce',
  membershipTierFourColor: '#ffed93',
};

const darkThemeValues = {
  landingPageBackgroundColor: '#14264b',
  landingPageBackgroundTopLayerColor: '#14264b',
  landingPageBackgroundBottomLayerColor: '#ba0c2f',
  landingPageCardColor: '##1e5550',
  landingPageTextColor: '#ffffff',
  authInputBackgroundColor: '#121212',
  mainPageBackgroundColor: '#f5f5f5',
  mainPageHeaderColor: '#ba0c2f',
  mainPageSidebarColor: '#202429',
  mainPageCardColor: '#202429',
  primaryTextColor: '#ced2d6',
  secondaryTextColor: '#9c9ca4',
  headingTextColor: '#5df891',
  menuTextColor: '#9c9ca4',
  primaryButtonColor: '#ba0c2f',
  secondaryButtonColor: '#596169',
  modalBackgroundColor: '#1a1e23',
  tabHighlightColor: '#ba0c2f',
  buttonTextColor: '#ffffff',
  tokenTextColor: '#ba0c2f',
  kudosTextColor: '#feb201',
  kudosIconColor: '#fd5900',
  dateTextColor: '#a3833f',
  successColor: '#33be51',
  errorColor: '#ff0000',
  warningColor: '#feb201',
  iconColor: '#b27300',
  membershipTierOneColor: '#c6cfd9',
  membershipTierTwoColor: '#9eddff',
  membershipTierThreeColor: '#ee7fce',
  membershipTierFourColor: '#ffed93',
};

export function generateMainTeam(theme: BackgroundTheme) {
  const themeValue =
    theme === BackgroundTheme.Light ? lightThemeValues : darkThemeValues;
  return {
    name: '',
    description: '',
    logo: '',
    appLogoImage: '',
    platformName: '',
    platformUrl: '',
    adminFirstName: '',
    adminLastName: '',
    adminEmail: '',
    adminPhoneNumber: '',
    tokenSaleToFan: 0,
    tokenSaleToSponsors: 0,
    price: 0,
    vaultTokenBalance: 0,
    teamWalletBalance: 0,
    kudosToTire1: 0,
    kudosToTire2: 1000,
    kudosToTire3: 2000,
    kudosToTire4: 5000,
    memberLevelName1: 'Starter',
    memberLevelName2: 'Avid',
    memberLevelName3: 'Super Fan',
    memberLevelName4: 'Fanatic',
    backgroundTheme: theme,
    landingPageHeroImage: '',
    tokenImage: '',
    primaryFont: FontType.Goldman,
    secondaryFont: FontType.Goldman,
    sportId: null,
    pwaIcon: '',
    ...themeValue,
  };
}
