export const SIGNUP_REWARD_LIMIT_COUNT = 100;
export const EARLY_SIGNUP_KUDOS_REWARD = 500;
export const EARLY_SIGNUP_TOKEN_REWARD = 1000;
export const REFERRAL_SIGNUP_TOKEN_REWARD = 1500;
export const REFERRAL_SIGNUP_KUDOS_REWARD = 500;
export const REFERRAL_PLAY_TOKEN_REWARD = 500;
export const REFERRAL_PLAY_KUDOS_REWARD = 200;
